# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AtList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for AtList

  pod 'LBTAComponents', '~> 0.1.9'

  pod 'TRON', '~> 2.0.0'

  pod 'Toucan', '~> 0.6'
  use_frameworks!
end
